import assert from 'node:assert/strict';
import { parseUsage, displayUsage, tokenIdentity, usageCredential, fetchUsage, createUsageLoader } from './src/codex-usage.ts';
const jwt = id => `fake.${Buffer.from(JSON.stringify({ 'https://api.openai.com/auth': { chatgpt_account_id: id } })).toString('base64url')}.fake`;
const fixture = { rate_limit: { primary_window: { used_percent: 23, reset_at: 2000000000, limit_window_seconds: 18000 }, secondary_window: { used_percent: 91, reset_at: 2000500000, limit_window_seconds: 604800 } } };
assert.equal(tokenIdentity(jwt('test')).accountId, 'test');
assert.equal(usageCredential({ access: jwt('test'), accountId: 'other' }), undefined);
assert.equal(tokenIdentity('bad-secret'), undefined);
const parsed = parseUsage(fixture);
assert.equal(parsed.windows[0].remaining, 77);
assert.equal(parsed.windows[1].remaining, 9);
const formatted = displayUsage(parsed, 1999999000000);
assert.equal(formatted.summary, '5h 77% left · Weekly 9% left');
assert.match(formatted.details[0], /5h resets .*in 0h 17m/);
assert.match(displayUsage(parsed, 2100000000000).details[0], /reset due/);
assert.match(displayUsage(parseUsage({})).summary, /unavailable/);
assert.equal(parseUsage({ rate_limit: { primary_window: { used_percent: NaN } } }).windows.length, 0);
assert.match(displayUsage(parseUsage({ rate_limit: { secondary_window: { used_percent: 50, limit_window_seconds: 604800 } } })).summary, /^Weekly/);
const signal = new AbortController().signal;
const credential = { access: jwt('test'), accountId: 'test' };
let calls = 0;
const fetcher = async (url, options) => {
 assert.equal(url, 'https://chatgpt.com/backend-api/wham/usage');
 assert.equal(options.headers['ChatGPT-Account-Id'], 'test');
 assert.equal(options.redirect, 'error'); calls++;
 return new Response(JSON.stringify(fixture));
};
assert.equal((await fetchUsage(credential, signal, fetcher)).windows.length, 2);
assert.match((await fetchUsage(credential, signal, async () => new Response('', { status: 401 }))).error, /expired/);
assert.match((await fetchUsage(credential, signal, async () => new Response('', { status: 429 }))).error, /HTTP 429/);
assert.equal(JSON.stringify(await fetchUsage(credential, signal, async () => { throw new Error('SECRET'); })).includes('SECRET'), false);
const loader = createUsageLoader(fetcher);
await loader(new Map([['work', credential]]), signal);
await loader(new Map([['work', credential]]), signal);
assert.equal(calls, 2);
await createUsageLoader(fetcher)(new Map([['work', credential], ['default', credential]]), signal);
assert.equal(calls, 3, 'Duplicate default/saved account requests should coalesce');
let active = 0, peak = 0;
const bounded = createUsageLoader(async () => { active++; peak = Math.max(peak, active); await new Promise(r => setTimeout(r, 5)); active--; return new Response(JSON.stringify(fixture)); });
await bounded(new Map(Array.from({ length: 8 }, (_, i) => [`account-${i}`, { access: jwt(String(i)), accountId: String(i) }])), signal);
assert.equal(peak, 3);
const aborted = new AbortController(); aborted.abort();
assert.equal((await bounded(new Map([['test', credential]]), aborted.signal)).size, 0);
console.log('PASS: identity validation, remaining limits, window labels, reset dates/countdowns, missing limits, HTTP errors, secret-safe failures, cache, bounded concurrency and cancellation.');
