[backdrop]
blur_intensity = 0.5
enabled = true
tint_intensity = 0.12

[bar.default]
background_opacity = 0.59999998658895493
contact_shadow = true
end = [
    "wg_proton",
    "wg_home",
    "wg_killswitch",
    "spacer3",
    "cpu",
    "ram",
    "spacer2",
    "tray",
    "notifications",
    "network",
    "battery",
    "session"
]
margin_edge = 0
margin_ends = 0
start = [ "workspaces", "spacer1", "media" ]
widget_spacing = 13

[idle]
behavior_order = [ "lock", "screen-off", "suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 600

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 120

    [idle.behavior.suspend]
    action = "suspend"
    enabled = true
    lock_before_suspend = true
    timeout = 900

[osd]
offset_y = 20
position = "bottom_center"

[shell]
font_family = "JetBrainsMono Nerd Font"
telemetry_enabled = false
ui_scale = 1.1000000089406967

    [shell.animation]
    speed = 4.0

    [shell.panel]
    control_center_placement = "floating"
    transparency_mode = "glass"

[theme]
builtin = "Catppuccin"
source = "builtin"

    [theme.templates]
    builtin_ids = [ "btop", "ghostty", "kitty", "niri", "starship" ]
    community_ids = [ "walker", "telegram", "yazi" ]

[wallpaper]
directory = "/home/hugo/Pictures/aesthetic-wallpapers/images"

    [wallpaper.default]
    path = "/home/hugo/Pictures/aesthetic-wallpapers/images/astronaut-planet.jpg"

    [wallpaper.last]
    path = "/home/hugo/Pictures/aesthetic-wallpapers/images/astronaut-planet.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/hugo/Pictures/aesthetic-wallpapers/images/astronaut-planet.jpg"

[weather]
address = "Lindås"

[widget.network]
show_label = false

[widget.spacer1]
type = "spacer"

[widget.spacer2]
length = 55
type = "spacer"

[widget.spacer3]
length = 55
type = "spacer"

[widget.sysmon]
display = "text"
show_label = false
stat = "ram_used"

[widget.wg_home]
fallback_glyph = "home"
scope = "shared"
script = "~/.config/noctalia-v5-test/noctalia/scripts/wireguard_status.lua"
status_command = "/home/hugo/.local/bin/wg-status-home"
toggle_command = "/home/hugo/.local/bin/wg-toggle-home"
tooltip = "WireGuard Home"
type = "scripted"

[widget.wg_killswitch]
fallback_glyph = "shield-check"
scope = "shared"
script = "~/.config/noctalia-v5-test/noctalia/scripts/wireguard_status.lua"
status_command = "/home/hugo/.local/bin/wg-status-killswitch"
toggle_command = "/home/hugo/.local/bin/wg-toggle-killswitch"
tooltip = "Kill Switch"
type = "scripted"

[widget.wg_proton]
fallback_glyph = "shield-lock"
scope = "shared"
script = "~/.config/noctalia-v5-test/noctalia/scripts/wireguard_status.lua"
status_command = "/home/hugo/.local/bin/wg-status-proton"
toggle_command = "/home/hugo/.local/bin/wg-toggle-proton"
tooltip = "WireGuard Proton"
type = "scripted"
