"$schema" = 'https://starship.rs/config-schema.json'

format = """
$hostname $directory $git_branch$git_status$nodejs$rust$golang$php$fill$time
$cmd_duration$character"""

[cmd_duration]
disabled = true

[fill]
symbol = ' '

[hostname]
ssh_only = false
style = "fg:4"
format = '[\[](fg:5)[@$hostname]($style)[\]](fg:5)'

[directory]
style = "fg:4"
format = '[\[](fg:5)[$path]($style)[\]](fg:5)'
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:2"
format = '[on](fg:5) [$symbol $branch]($style)'

[git_status]
style = "fg:1"
format = '([$all_status$ahead_behind]($style) )'
stashed = '≡'
staged = '[+$count](fg:2)'
modified = '[~$count](fg:3)'
untracked = '[?$count](fg:4)'
deleted = '[-$count](fg:1)'
ahead = '⇡$count'
behind = '⇣$count'
conflicted = '✖'

[nodejs]
symbol = ""
style = "fg:3"
format = ' [\[](fg:5)[$symbol $version]($style)[\]](fg:5)'

[rust]
symbol = ""
style = "fg:4"
format = ' [\[](fg:5)[$symbol $version]($style)[\]](fg:5)'

[golang]
symbol = ""
style = "fg:6"
format = ' [\[](fg:5)[$symbol $version]($style)[\]](fg:5)'

[php]
symbol = ""
style = "fg:13"
format = ' [\[](fg:5)[$symbol $version]($style)[\]](fg:5)'

[time]
disabled = false
time_format = "%R"
style = "fg:5"
format = ' $time'

[os]
disabled = false
style = "fg:4"
format = '[$symbol]($style)'

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
EndeavourOS = " "
Fedora = "󰣛 "
Gentoo = "󰣨 "
Linux = "󰌽 "
Macos = "󰀵 "
Manjaro = " "
Mint = "󰣭 "
Pop = " "
Raspbian = "󰐿 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
SUSE = " "
Ubuntu = "󰕈 "
Windows = "󰍲 "
