# Input overrides for Norwegian PC keyboard + touchpad
input {
  kb_layout = nobrackets_pc
  kb_options =

  sensitivity = 0.23
  accel_profile = adaptive
  natural_scroll = true
  scroll_factor = 1
  # accel_profile = custom 1.0 0.0 0.11 0.25 0.43 0.65 0.92 1.24 1.68 2.22

  repeat_rate = 45
  repeat_delay = 300

  touchpad {
    natural_scroll = false
    clickfinger_behavior = true
    scroll_factor = 0.25
  }
}
# Scroll speed per app
windowrule = scroll_touchpad 10.0, match:class (kitty)
windowrule = scroll_touchpad 0.5, match:class (brave-browser)
windowrule = scroll_touchpad 1.0, match:class (org.mozilla.firefox)

# Enable touchpad gestures for changing workspaces (3-finger horizontal swipe)
gesture = 3, horizontal, workspace
gestures:workspace_swipe_distance = 80

cursor {
    no_hardware_cursors = true
    no_warps = true
}
