dwindle {
    preserve_split = true
}

general {
    gaps_in = 4
    gaps_out = 4
    border_size = 1
}

decoration {
    rounding = 4
    active_opacity = 0.97
    inactive_opacity = 0.90
    blur {
        enabled = false
    }
    shadow {
        enabled = false
    }
}

animations {
    enabled = true
    bezier = snappy, 0.2, 1.0, 0.3, 1.0
    animation = windows, 1, 2, snappy, popin 80%
    animation = windowsMove, 1, 2, snappy
    animation = fade, 1, 2, snappy
    animation = workspaces, 1, 2, snappy, slide
    animation = layers, 1, 2, snappy, fade
}

render {
    direct_scanout = false
}


# No gaps or borders on ws1
workspace = 1, gapsin:0, gapsout:0, border:false, rounding:false

# No gaps on ws2
workspace = 2, gapsin:1

# Global opacity override
windowrule = opacity 1.0 override 0.98 override, match:class .*

# Terminal-only opacity
windowrule = opacity 0.98 override 0.95 override, match:class ^(kitty|kitty-dropterm|ghostty|com.mitchellh.ghostty)$
